INSERT INTO webcal_user ( cal_login, cal_passwd, cal_firstname, cal_lastname, cal_is_admin, cal_is_beancounter, cal_household, cal_birthdate ) VALUES ( 'jkimdon', 'ae7a69fb6570aaeada5e8718ea54570e', 'Joey', 'Kimdon', 'Y', 'Y', 'Kimdons', '19770904' );
INSERT INTO webcal_user ( cal_login, cal_passwd, cal_firstname, cal_lastname, cal_is_admin, cal_is_beancounter, cal_household, cal_birthdate ) VALUES ( 'dkimdon', 'ae7a69fb6570aaeada5e8718ea54570e', 'David', 'Kimdon', 'N', 'N', 'Kimdons', '19751223' );
INSERT INTO webcal_user ( cal_login, cal_passwd, cal_firstname, cal_lastname, cal_is_admin, cal_is_beancounter, cal_household, cal_birthdate ) VALUES ( 'akimdon', 'ae7a69fb6570aaeada5e8718ea54570e', 'Aria', 'Kimdon', 'N', 'N', 'Kimdons', '20050914' );
INSERT INTO webcal_meal ( cal_id, cal_club_id, cal_date, cal_time, cal_suit, cal_walkins, cal_head_chef, cal_num_cooks, cal_num_cleanup, cal_num_setup, cal_num_other_crew, cal_menu, cal_notes ) VALUES ( '1', '1', '20070910', '173000', 'club', 'D', 'not selected', '2', '2', '2', '0', 'green beans and corn', 'This is the From-The-CoHo-Garden Club' );
INSERT INTO webcal_meal ( cal_id, cal_club_id, cal_date, cal_time, cal_suit, cal_walkins, cal_head_chef, cal_num_cooks, cal_num_cleanup, cal_num_setup, cal_num_other_crew, cal_menu, cal_notes ) VALUES ( '2', '1', '20070917', '173000', 'club', 'D', 'not selected', '2', '2', '2', '0', '', 'This is the From-The-CoHo-Garden Club' );
INSERT INTO webcal_meal ( cal_id, cal_club_id, cal_date, cal_time, cal_suit, cal_walkins, cal_head_chef, cal_num_cooks, cal_num_cleanup, cal_num_setup, cal_num_other_crew, cal_menu, cal_notes ) VALUES ( '3', '1', '20070924', '173000', 'club', 'D', 'not selected', '2', '2', '2', '0', '', 'This is the From-The-CoHo-Garden Club' );
INSERT INTO webcal_meal ( cal_id, cal_club_id, cal_date, cal_time, cal_suit, cal_walkins, cal_head_chef, cal_num_cooks, cal_num_cleanup, cal_num_setup, cal_num_other_crew, cal_menu, cal_notes ) VALUES ( '4', '1', '20071001', '173000', 'club', 'D', 'not selected', '2', '2', '2', '0', '', 'This is the From-The-CoHo-Garden Club' );
INSERT INTO webcal_meal ( cal_id, cal_club_id, cal_date, cal_time, cal_suit, cal_walkins, cal_head_chef, cal_num_cooks, cal_num_cleanup, cal_num_setup, cal_num_other_crew, cal_menu, cal_notes ) VALUES ( '5', '1', '20071008', '173000', 'club', 'D', 'not selected', '2', '2', '2', '0', '', 'This is the From-The-CoHo-Garden Club' );
INSERT INTO webcal_meal ( cal_id, cal_club_id, cal_date, cal_time, cal_suit, cal_walkins, cal_head_chef, cal_num_cooks, cal_num_cleanup, cal_num_setup, cal_num_other_crew, cal_menu, cal_notes ) VALUES ( '6', '2', '20070904', '180000', 'club', 'D', 'not selected', '2', '2', '2', '0', 'berries and sauce', 'This is the Leftovers Club' );
INSERT INTO webcal_meal ( cal_id, cal_club_id, cal_date, cal_time, cal_suit, cal_walkins, cal_head_chef, cal_num_cooks, cal_num_cleanup, cal_num_setup, cal_num_other_crew, cal_menu, cal_notes ) VALUES ( '7', '2', '20070911', '180000', 'club', 'D', 'not selected', '2', '2', '2', '0', 'berries and sauce', 'This is the Leftovers Club' );
INSERT INTO webcal_meal ( cal_id, cal_club_id, cal_date, cal_time, cal_suit, cal_walkins, cal_head_chef, cal_num_cooks, cal_num_cleanup, cal_num_setup, cal_num_other_crew, cal_menu, cal_notes ) VALUES ( '8', '2', '20070918', '180000', 'club', 'D', 'not selected', '2', '2', '2', '0', 'berries and sauce', 'This is the Leftovers Club' );
INSERT INTO webcal_meal ( cal_id, cal_club_id, cal_date, cal_time, cal_suit, cal_walkins, cal_head_chef, cal_num_cooks, cal_num_cleanup, cal_num_setup, cal_num_other_crew, cal_menu, cal_notes ) VALUES ( '9', '0', '20070913', '183000', 'wild', 'E', 'not selected', '3', '2', '2', '0', 'baby food', 'babies only' )